// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netcore.Data;

namespace TCTInventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201107163952_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("netcore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("ApplicationUserRole")
                        .HasColumnType("bit");

                    b.Property<bool>("BranchRole")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CustomerLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("CustomerRole")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HomeRole")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductRole")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchaseOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchaseOrderRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivingLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivingRole")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesOrderRole")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShipmentLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentRole")
                        .HasColumnType("bit");

                    b.Property<bool>("StockRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferInLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferInRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOrderRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOutLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOutRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("VendorLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("VendorRole")
                        .HasColumnType("bit");

                    b.Property<bool>("WarehouseRole")
                        .HasColumnType("bit");

                    b.Property<bool>("isSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("profilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("netcore.Models.Invent.Branch", b =>
                {
                    b.Property<int>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("isDefaultBranch")
                        .HasColumnType("bit");

                    b.Property<string>("province")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("branchId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("netcore.Models.Invent.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("customerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("netcore.Models.Invent.CustomerLine", b =>
                {
                    b.Property<int>("customerLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("salutation")
                        .HasColumnType("int");

                    b.Property<string>("workEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("customerLineId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("productType")
                        .HasColumnType("int");

                    b.Property<string>("serialNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("uom")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrder", b =>
                {
                    b.Property<int>("purchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliveryAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("picVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("poDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("purchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("purchaseOrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("purchaseReceiveNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceNumberExternal")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("top")
                        .HasColumnType("int");

                    b.Property<decimal>("totalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vendorId")
                        .HasColumnType("int");

                    b.HasKey("purchaseOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("vendorId");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.Property<int>("purchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<int>("purchaseOrderId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("purchaseOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("PurchaseOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Receiving", b =>
                {
                    b.Property<int>("receivingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("purchaseOrderId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<DateTime>("receivingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("receivingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("vendorDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("vendorId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<string>("vendorInvoice")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("warehouseId")
                        .HasColumnType("int");

                    b.HasKey("receivingId");

                    b.HasIndex("branchId");

                    b.HasIndex("purchaseOrderId");

                    b.HasIndex("vendorId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Receiving");
                });

            modelBuilder.Entity("netcore.Models.Invent.ReceivingLine", b =>
                {
                    b.Property<int>("receivingLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<float>("qtyReceive")
                        .HasColumnType("real");

                    b.Property<int>("receivingId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<int>("warehouseId")
                        .HasColumnType("int");

                    b.HasKey("receivingLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("receivingId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ReceivingLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrder", b =>
                {
                    b.Property<int>("salesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<string>("deliveryAddress")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("picCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberExternal")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("salesOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("salesOrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("salesShipmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("soDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("top")
                        .HasColumnType("int");

                    b.Property<decimal>("totalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("salesOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrderLine", b =>
                {
                    b.Property<int>("salesOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<int>("salesOrderId")
                        .HasColumnType("int")
                        .HasMaxLength(38);

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("salesOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("salesOrderId");

                    b.ToTable("SalesOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Shipment", b =>
                {
                    b.Property<int>("shipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<string>("customerPO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("expeditionMode")
                        .HasColumnType("int");

                    b.Property<int>("expeditionType")
                        .HasColumnType("int");

                    b.Property<string>("invoice")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("salesOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("shipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("shipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("warehouseId")
                        .HasColumnType("int");

                    b.HasKey("shipmentId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("salesOrderId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("netcore.Models.Invent.ShipmentLine", b =>
                {
                    b.Property<int>("shipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<float>("qtyShipment")
                        .HasColumnType("real");

                    b.Property<int>("shipmentId")
                        .HasColumnType("int");

                    b.Property<int>("warehouseId")
                        .HasColumnType("int");

                    b.HasKey("shipmentLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("shipmentId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ShipmentLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferIn", b =>
                {
                    b.Property<int>("transferInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("branchFrombranchId")
                        .HasColumnType("int");

                    b.Property<int>("branchIdFrom")
                        .HasColumnType("int");

                    b.Property<string>("branchIdTo")
                        .HasColumnType("nvarchar(38)")
                        .HasMaxLength(38);

                    b.Property<int?>("branchTobranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("transferInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferInNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("transferOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("warehouseFromwarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdFrom")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdTo")
                        .HasColumnType("int");

                    b.Property<int?>("warehouseTowarehouseId")
                        .HasColumnType("int");

                    b.HasKey("transferInId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferIn");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferInLine", b =>
                {
                    b.Property<int>("transferInLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<int>("transferInId")
                        .HasColumnType("int");

                    b.HasKey("transferInLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferInId");

                    b.ToTable("TransferInLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrder", b =>
                {
                    b.Property<int>("transferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("branchFrombranchId")
                        .HasColumnType("int");

                    b.Property<string>("branchIdFrom")
                        .HasColumnType("nvarchar(38)")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasColumnType("nvarchar(38)")
                        .HasMaxLength(38);

                    b.Property<int?>("branchTobranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("isIssued")
                        .HasColumnType("bit");

                    b.Property<bool>("isReceived")
                        .HasColumnType("bit");

                    b.Property<string>("picName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("transferOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("transferOrderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("warehouseFromwarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdFrom")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdTo")
                        .HasColumnType("int");

                    b.Property<int?>("warehouseTowarehouseId")
                        .HasColumnType("int");

                    b.HasKey("transferOrderId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrderLine", b =>
                {
                    b.Property<int>("transferOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<int>("transferOrderId")
                        .HasColumnType("int");

                    b.HasKey("transferOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOrderId");

                    b.ToTable("TransferOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOut", b =>
                {
                    b.Property<int>("transferOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("branchFrombranchId")
                        .HasColumnType("int");

                    b.Property<int>("branchIdFrom")
                        .HasColumnType("int");

                    b.Property<string>("branchIdTo")
                        .HasColumnType("nvarchar(38)")
                        .HasMaxLength(38);

                    b.Property<int?>("branchTobranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("transferOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("transferOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferOutNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("warehouseFromwarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdFrom")
                        .HasColumnType("int");

                    b.Property<int>("warehouseIdTo")
                        .HasColumnType("int");

                    b.Property<int?>("warehouseTowarehouseId")
                        .HasColumnType("int");

                    b.HasKey("transferOutId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOut");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOutLine", b =>
                {
                    b.Property<int>("transferOutLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<int>("transferOutId")
                        .HasColumnType("int");

                    b.HasKey("transferOutLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOutId");

                    b.ToTable("TransferOutLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Vendor", b =>
                {
                    b.Property<int>("vendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HasChild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("vendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("vendorId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorLine", b =>
                {
                    b.Property<int>("vendorLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("salutation")
                        .HasColumnType("int");

                    b.Property<int>("vendorId")
                        .HasColumnType("int");

                    b.Property<string>("workEmail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("vendorLineId");

                    b.HasIndex("vendorId");

                    b.ToTable("VendorLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Warehouse", b =>
                {
                    b.Property<int>("warehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("warehouseId");

                    b.HasIndex("branchId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.CustomerLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany("customerLine")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderLine")
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.Receiving", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany()
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.ReceivingLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Receiving", "receiving")
                        .WithMany("receivingLine")
                        .HasForeignKey("receivingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany("salesOrderLine")
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.Shipment", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany()
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.ShipmentLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Shipment", "shipment")
                        .WithMany("shipmentLine")
                        .HasForeignKey("shipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferIn", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferInLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.TransferIn", "transferIn")
                        .WithMany("transferInLine")
                        .HasForeignKey("transferInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany("transferOrderLine")
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOut", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOutLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("netcore.Models.Invent.TransferOut", "transferOut")
                        .WithMany("transferOutLine")
                        .HasForeignKey("transferOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany("vendorLine")
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("netcore.Models.Invent.Warehouse", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
